server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  application:
    name: user
  config:
    import: optional:file:./user/.env[.properties]
  datasource:
    url: jdbc:postgresql://db:5432/postgres
#    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
#    password: mysecretpassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
