version: '3.5'

services:
  
  eureka-service:
    image: microservices-eureka:latest
    build: eureka
    container_name: eureka-server-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8761" ]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend-service:
    image: microservices-blog-frontend:latest
    build: blog-frontend
    container_name: frontend
    ports:
      - '3000:3000'


  gateway-service:
    image: microservices-gateway:latest
    build: gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy

  blog-service:
    image: microservices-blog:latest
    build: blog
    container_name: blog-service
    environment:
      DB_URL: jdbc:postgresql://blog-database:5432/blog-db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy
      blog-database:
        condition: service_started

  blog-database:
    container_name: blog-database
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog-db

  db:
    container_name: users-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  user-service:
    image: microservices-user:latest
    build: user
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy
      db:
        condition: service_started

  news-service:
    image: microservices-news:latest
    build: news
    container_name: news-service
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy

  job-service:
    image: microservices-job:latest
    build: job
    container_name: job-service
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy