version: '3.5'

services:
  
  eureka-service:
    image: microservices-eureka:latest
    build: eureka
    container_name: eureka-server-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8761" ]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend-service:
    image: microservices-blog-frontend:latest
    build: blog-frontend
    container_name: frontend
    ports:
      - '3000:3000'


  gateway-service:
    image: microservices-gateway:latest
    build: gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER://kafka:9092,LISTENER_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  blog-service:
    image: microservices-blog:latest
    build: blog
    container_name: blog-service
    environment:
      DB_URL: jdbc:postgresql://blog-database:5432/blog-db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy
      blog-database:
        condition: service_started
      kafka:
        condition: service_started

  blog-database:
    container_name: blog-database
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog-db

  db:
    container_name: users-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  user-service:
    image: microservices-user:latest
    build: user
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy
      db:
        condition: service_started
      kafka:
        condition: service_started
