version: '3.5'

services:
  
  eureka-service:
    image: microservices-eureka:latest
    build: eureka
    container_name: eureka-server-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8761" ]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway-service:
    image: microservices-gateway:latest
    build: gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy

  db:
    container_name: users-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresqlcd

  user-service:
    image: microservices-user:latest
    build: user
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy
      db:
        condition: service_started