version: '3.5'

services:
  
  eureka-service:
    image: microservices-eureka:latest
    build: eureka
    container_name: eureka-server-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8761" ]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway-service:
    image: microservices-gateway:latest
    build: gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-service:8761/eureka/
    depends_on:
      eureka-service:
        condition: service_healthy