server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  application:
    name: gateway
  config:
    import: optional:file:./gateway/.env[.properties]

  cloud:
    gateway:
      routes:
        - id: users
          uri: http://user-service:8081
          predicates:
            - Path=/users/**