server:
  port: 8080

security:
  jwt:
    secret: MTA1NDQ2NDYyMjkxODQ3NjI0NjM4NjUxNTYxZGZnMTU2MTQ4ZGY5NDE4MTk0OTg=

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    renewalIntervalInSecs: 10

spring:
  application:
    name: gateway
  config:
    import: optional:file:./gateway/.env[.properties]
  cloud:
    gateway:
      routes:
        - id: posts
          uri: lb://blog-service
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/posts(?<remaining>.*), /api/v1/posts${remaining}
        - id: users
          uri: lb://user
          predicates:
            - Path=/users/**
        - id: news
          uri: lb://news-service
          predicates:
            - Path=/news/**
          filters:
            - RewritePath=/news(?<remaining>.*), /api/v1/news${remaining}
        - id: jobs
          uri: lb://job-service
          predicates:
            - Path=/jobs/**
          filters:
            - RewritePath=/jobs(?<remaining>.*), /api/v1/jobs${remaining}
        - id: subscriptions
          uri: lb://subscription-service
          predicates:
            - Path=/subscriptions/**
          filters:
            - RewritePath=/subscriptions(?<remaining>.*), /api/v1/subscriptions${remaining}
        - id: subscriptions-swagger
          uri: lb://subscription-service
          predicates:
            - Path=/v3/api-docs/subscriptions
          filters:
            - name: CircuitBreaker
              args:
                name: subscriptionBreaker
                fallbackUri: forward:/fb/subscriptions/
        - id: subscriptions-redirect
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/subscriptions/**
          filters:
            - RewritePath=/api/v1/subscriptions(?<remaining>.*), /subscriptions${remaining}

        - id: posts-swagger
          uri: lb://blog-service
          predicates:
            - Path=/v3/api-docs/posts
          filters:
            - name: CircuitBreaker
              args:
                name: postBreaker
                fallbackUri: forward:/fb/posts/
        - id: posts-redirect
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - RewritePath=/api/v1/posts(?<remaining>.*), /posts${remaining}

        - id: users-swagger
          uri: lb://user
          predicates:
            - Path=/users/* , /v3/api-docs/users
          filters:
            - name: CircuitBreaker
              args:
                name: userBreaker
                fallbackUri: forward:/fb/users/