server:
  port: 0

spring:
  application:
    name: job-service

  config:
    import: optional:file:./job/.env[.properties]

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
